coverage:
  round: down
  status:
    project:
      default:
        target: 50%
        if_ci_failed: error
    patch:
      default:
        target: 50%
        if_ci_failed: error

github_checks: false
