name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - 'gaul/**'
      - 'tests/**'
      - 'examples/**'

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
        with:
          poetry-preview: true
      - name: Check Poetry version
        run: poetry --version
      - name: Set up Nox
        run: pip3 install nox==2022.1.7
      - name: Run Nox tests and lints
        run: nox -p ${{ matrix.python-version }}
      - name: Check coverage
        if: ${{ success() }}
        run: nox -p ${{ matrix.python-version }} -s coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
