name: tests
on: push
jobs: 
  tests:
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: Set up Nox
        uses: pip3 install nox==2022.1.7
      - name: Run Nox tests and lints
        uses: nox -p ${{ matrix.python-version }}
      - name: Check coverage
        uses: nox -p ${{ matrix.python-version }} -s coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
